apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delete
  labels:
    app: delete
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: delete-task.achinta.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: delete
            port: 
              number: 80
